from __future__ import annotations

import sys
import os
import pandas as pd

# --- REPRODUCIBILITY NOTES ---
# 
# The input for this script is the synthetic data generated by the self-contained
# demo (Task 2), located at 'demo_output/temp_data_input.csv'.
# 
# To replicate the exact analysis and generate the output files (which are 
# ignored by .gitignore), the script should be executed from the project root 
# directory using the following command:
#
#     python demo/analyse_from_csv.py demo_output/temp_data_input.csv
#
# -----------------------------

# Ensure the package is importable
try:
    from cluster_maker.data_analyser import calculate_extended_statistics
    from cluster_maker.data_exporter import export_summary_report
except ImportError:
    current_dir = os.path.dirname(os.path.abspath(__file__))
    parent_dir = os.path.dirname(current_dir)
    if parent_dir not in sys.path:
        sys.path.append(parent_dir)
    from cluster_maker.data_analyser import calculate_extended_statistics
    from cluster_maker.data_exporter import export_summary_report

OUTPUT_DIR = "demo_output"

def print_header(title: str):
    """Helper to print a nice header."""
    print("\n" + "=" * 80)
    print(f" {title}")
    print("=" * 80 + "\n")

def main() -> None:
    print_header("Statistical Analysis Tool")

    # Argument Validation
    if len(sys.argv) != 2:
        print("ERROR: Invalid number of arguments.")
        print("Usage: python demo/analyse_from_csv.py <path/to/input.csv>")
        print("\nExample: python demo/analyse_from_csv.py demo_output/temp_data_input.csv")
        sys.exit(1)

    input_path = sys.argv[1]
    
    if not os.path.exists(input_path):
        print(f"ERROR: The file '{input_path}' was not found.")
        sys.exit(1)

    print(f"Target File: {input_path}")
    print("-" * 80)

    # Read CSV
    print("\n[Step 1] Loading Data...")
    try:
        df = pd.read_csv(input_path)
        print(f" > Success. Loaded {len(df)} rows and {len(df.columns)} columns.")
    except Exception as e:
        print(f"FATAL ERROR: Could not read the CSV file.\nReason: {e}")
        sys.exit(1)
        
    # Compute Summary
    print("\n[Step 2] Computing Extended Statistics...")
    print(" (Calculates Mean, Std Dev, Min, Max, and Missing Values for all numeric columns)")
    
    try:
        summary_df = calculate_extended_statistics(df)
    except Exception as e:
        print(f"FATAL ERROR during analysis: {e}")
        sys.exit(1)

    if summary_df.empty:
        print(" > WARNING: No numeric columns found to analyse.")
    else:
        print(f" > Computed statistics for {len(summary_df)} numeric columns.")

    # Export Results
    print("\n[Step 3] Exporting Reports...")
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    csv_output_path = os.path.join(OUTPUT_DIR, "analysis_summary.csv")
    txt_output_path = os.path.join(OUTPUT_DIR, "analysis_summary.txt")

    try:
        export_summary_report(summary_df, csv_output_path, txt_output_path)
    except Exception as e:
        print(f"FATAL ERROR during export: {e}")
        sys.exit(1)

    # --- FEEDBACK FIX: Explicit File Summary at End ---
    print_header("Summary of Saved Files")
    print(f"Reports have been generated in '{OUTPUT_DIR}':\n")
    print(f"{'FILE':<30} | {'DESCRIPTION':<40}")
    print("-" * 75)
    print(f"{'analysis_summary.csv':<30} | Raw statistical data (spreadsheet friendly)")
    print(f"{'analysis_summary.txt':<30} | Formatted report (human readable)")
    print("-" * 75)
    print("\nAnalysis completed successfully.")

if __name__ == "__main__":
    main()